telegram_bot_token: "8103354983:AAGw6mAfAOzK7q53VyuJ37jFyJTXZw2hokw" #change it
maintenance: false #turn it to true to force the bot to go into maintanance mode.
db_path: "db/database.db"
max_users: 3000
traffic_limit: 8716192768 #5 GB
outline_ip: "144.172.117.211"
telegram_channel_id: "@Download_Download"
domain: "144.172.117.211"
ip: "144.172.117.211"